windowed: BasicVision_Windowed.cpp
	g++ `pkg-config --cflags opencv` BasicVision_Windowed.cpp -o BasicVision_Windowed `pkg-config --libs opencv`

std: BasicVision.cpp
	g++ `pkg-config --cflags opencv` BasicVision.cpp -o BasicVision `pkg-config --libs opencv`
